name: Build app and release
on:
  push:
    branches:
      - main
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
        release_branches: main
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build application
      run: npm run make
      run: mv "out/make/squirrel.windows/x64/mineman-launcher-0.1.0 Setup.exe" "out/make/squirrel.windows/x64/mineman-launcher-${{ steps.tag_version.outputs.new_tag }}-setup.exe"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          out/make/squirrel.windows/x64/mineman-launcher-${{ steps.tag_version.outputs.new_tag }}-setup.exe
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
